#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libarchive-c
Version  : 1.0
Release  : 4
URL      : https://pypi.python.org/packages/30/56/3315f6f5a9761955c4109db24f407bb96a343f37e09e5ffcd9c0df45c461/libarchive-c-1.0.tar.gz
Source0  : https://pypi.python.org/packages/30/56/3315f6f5a9761955c4109db24f407bb96a343f37e09e5ffcd9c0df45c461/libarchive-c-1.0.tar.gz
Summary  : Python interface to libarchive
Group    : Development/Tools
License  : LGPL-2.1+
Requires: libarchive-c-python
BuildRequires : libarchive-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
A Python interface to libarchive. It uses the standard ctypes_ module to
dynamically load and access the C library.

%package python
Summary: python components for the libarchive-c package.
Group: Default

%description python
python components for the libarchive-c package.


%prep
%setup -q -n libarchive-c-1.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484552107
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484552107
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
